### ISSUE TITLE
--ignore-scrolling does not work with gentoo

### ISSUE THREAD

**Issue by toniz4** [Airblader/unclutter-xfixes#58] opened 2020-08-13 11:45 UTC
On gentoo the flag --ignore-scrolling apparently does not make a difference, i tried compiling from the repo and got the same problem. I'm using a trackpoint, scrolling with the middle button, but the same setup was working in arch just fine.

**Comment by Airblader** [comment] 2020-08-13 11:57
Can you verify using xev which buttons are being pressed? It could be that it used something other than 4 and 5.

**Comment by toniz4** [comment] 2020-08-13 21:33
the middle button only notify a button release event, and when i'm scrolling,i'm only getting 4 and 5 events

**Comment by chelovechishko** [comment] 2020-08-14 06:04
It is just a duplicate of #47

**Comment by Airblader** [comment] 2020-08-14 07:28
Indeed, this seems to be the same issue, thanks.

@toniz4 Can you try using `--jitter 1`?

**Comment by toniz4** [comment] 2020-08-14 18:01
with ```--jiter 1``` with the mouse works as intended, but i have the same issue with the trackpoint

**Comment by Airblader** [comment] 2020-08-18 12:07
Can you run the same experiments with the trackpoint? Are we sure there are no non-scrolling events?

**Comment by toniz4** [comment] 2020-09-25 07:58
sorry for the late response, my trackpoint reports button 6 events when scrolling "harder". It might be a libinput bug, but i made a pr if you are willing to merge it. 

Thanks!

**Comment by Airblader** [comment] 2020-09-25 08:56
@toniz4 If you do end up filing a bug please feel free to link it here for context. :-)

**Comment by chelovechishko** [comment] 2020-09-25 13:16
As for me (with mouse) `button 6` scrolls to the left, so i guess:
https://gitlab.freedesktop.org/libinput/libinput/-/issues/305

> PS: not related to this problem, but I always wondered why does libinput ship with horizontal scrolling enabled on trackpoints by default? I really don't think that there is a sensible way one can use it with a trackpoint. For example, when you scroll a web site down via the middle button, it is sufficient to move the trackpoint just a tiny bit to the left or to the right and Firefox would immediately go to the previous or the next page respectively. Very annoying and inconvenient. So setting HorizontalScrolling to false via xorg.conf.d is one of the first things I need to do on any ThinkPad or Dell with a trackpoint.

**Comment by toniz4** [comment] 2020-09-25 14:39
@chelovechishko  apparently for me too, after some tinkering i discovered that i have to ignore button 7 too. But when i try to debug this with xev i don't see button 7/6 when scrolling horizontally only buttons 4/5. Disabling HorizontalScrolling in the xorg configs works too, but i use horizontal scrolling sometimes. Weird stuff. Do you know any better way to debug this?

**Comment by Airblader** [comment] 2020-09-25 15:01
I forgot about this earlier, but instead of ignore scrolling you can use ignore buttons to specify other buttons to ignore, see https://github.com/Airblader/unclutter-xfixes/pull/41. That should give you a good workaround.

**Comment by chelovechishko** [comment] 2020-09-25 15:50
You could set debug output on the program to see only number of event
instead of `xev -event button`.

https://gitlab.freedesktop.org/libinput/libinput/-/blob/master/doc/user/scrolling.rst

> Scroll movements provide vertical and horizontal directions, each scroll event contains both directions where applicable, see libinput_event_pointer_get_axis_value(). libinput does not provide separate toggles to enable or disable horizontal scrolling. Instead, horizontal scrolling is always enabled. This is intentional, libinput does not have enough context to know when horizontal scrolling is appropriate for a given widget. The task of filtering horizontal movements is up to the caller.


Maybe just disable simultaneous (both directions) scrolling if the
problem only with this?

**Comment by toniz4** [comment] 2020-09-25 16:00
I did some research and apparently button 6 and 7 is for horizontal scrolling, as the libinput(4) manpage says:

>BUTTON MAPPING
>     X clients receive events with logical button numbers, where 1, 2, 3 are  usually
>     interpreted  as  left,  middle, right and logical buttons 4, 5, 6, 7 are usually
>     interpreted as scroll up, down, left, right. The fourth and fifth physical  but‐
>     tons  on a device will thus send logical buttons 8 and 9.

**Comment by Airblader** [comment] 2020-09-25 16:02
Yeah, but I'd like to not change the default behavior here since this can be achieved with another flag already anyway.

**Comment by mjkalyan** [comment] 2020-11-15 22:46
Should probably close this issue as it's a result of sending other button events and not a bug. `--ignore-scrolling` works fine for me (on gentoo, not that it would matter here) with `--jitter 1`

**Comment by Airblader** [comment] 2020-11-16 06:39
I'll close this, but I'll make sure to mention this in the man page.

**Closed** 2020-11-16 06:39 UTC
